name: Python testing application


on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
    - name: Python Pylint Github Action
      uses: fylein/python-pylint-github-action@v4
      with:
        args: pip install pylint
    - name: autopep8
      # You may pin to the exact commit or the version.
      # uses: peter-evans/autopep8@1ba8b3249d3cf04922eecd66fc6a024072f4a7b0
      uses: peter-evans/autopep8@v1.2.1
      with:
        # Arguments to pass to autopep8
        args: # default is --help
